apiVersion: v1
kind: Service
metadata:
  name: reposage-server
  labels:
    app: reposage-server
spec:
  type: ClusterIP
  selector:
    app: reposage-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
